ekf_filter_node:
  ros__parameters:
    frequency: 20.0
    two_d_mode: true
    transform_time_offset: 0.0
    sensor_timeout: 0.1
    publish_tf: true
    publish_acceleration: true
    debug: true
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    imu0: "/zed/zed_node/imu/data"
    imu0_remove_gravitational_acceleration: true
    imu0_config: [false, false, false,   # position (x, y, z) 
                  true,  true,  true,    # orientation (roll, pitch, yaw)
                  false, false, false,   # linear velocity (x, y, z)
                  false, false, false,    # angular velocity (roll rate, pitch rate, yaw rate)
                  false, false, false]    # linear acceleration (ax, ay, az)
    imu0_differential: false
    imu0_relative: false
